apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: java
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
---
apiVersion: v1 
kind: Service 
metadata:
  name: java 
  labels:
    app: java
spec: 
  selector:
    app: java
  ports:
    - name: service-port
      port: 5153
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: java 
  labels:
    app: java
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: deployment-port
          image: edgareor/crud-rest-java-mysql-2023:version1
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8081
          resources:
           requests:
             cpu: "300m"
             memory: "300Mi"
           limits: 
             cpu: "400m"
             memory: "400Mi"
          env:
            - name: VAR_TEST
              value: "valorTest"